name: Code Vulnerability Check

on:
  push:
    branches:
      - 'main'
      - 'releases/*'
  pull_request:
    branches:
      - 'main'
      - 'releases/*'

jobs:
  security_scan:
    runs-on: ubuntu-latest

    env:
      PROJECT_NAME: OperationResult
      SOLUTION_DIRECTORY: OperationResult.Net

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get .NET Version from Project File
      id: get-dotnet-version
      run: echo "::set-output name=version::$(grep -oP '<TargetFramework>(.*)<\/TargetFramework>' YourProject.csproj | grep -oP '\d\.\d')"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ steps.get-dotnet-version.outputs.version }}

    - name: Restore dependencies
      run: |
        cd ${{ env.SOLUTION_DIRECTORY }}
        dotnet restore

    - name: Install OWASP Dependency-Check
      run: |
        sudo apt-get install -y openjdk-11-jre
        sudo apt-get install -y --no-install-recommends \
          python3 \
          python3-pip \
          python3-setuptools
        pip3 install --upgrade pip
        pip3 install --no-cache-dir --user dependency-check

        ~/.local/bin/dependency-check --scan . --project ${{ env.PROJECT_NAME }} --out $HOME/dependency-check

    - name: Upload results
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: dependency-check-results
        path: $HOME/dependency-check
